databases:
  - name: acme-salary-db
    databaseName: salarydb
    user: salary
    plan: free

services:
  - type: web
    name: acme-salary-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: acme-salary-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: acme-salary-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: acme-salary-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: acme-salary-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: acme-salary-db
          property: password

  - type: web
    name: acme-salary-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    envVars:
      - key: BACKEND_URL
        fromService:
          name: acme-salary-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
