spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/salarydb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:salary}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:salary}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# SQL & Hibernate formatting
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Logging levels
logging.level.com.acme.salary=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.transaction=DEBUG
